#!/bin/bash

YOUREMAIL="email@email.com"
INTFC=eth0

IPADDRESS=$(ifconfig $INTFC | sed -n 's/.*inet addr:\([^ ]*\).*/\1/p')
OldIP=$(<~/.current_ip)

if [[ ${IPADDRESS} != ${OldIP} ]]; then
echo "Your new IP address is ${IPADDRESS} (old address was ${OldIP} )" | mail -s "IP address change" $YOUREMAIL
echo ${IPADDRESS} > ~/.current_ip
fi
