#!/bin/bash

# Display CPU temperature. Originally inspired by Brian Heckathorne.
# Only works on the Beaglebone Black, under debian!

# ToDo: Format the temperature output so its XX.X rather than XX000.
#	Check to see if this is a BBB, otherwise exit -1!
#	Accept an input variable to just display XX with no decimals.

if [ -f /sys/class/hwmon/hwmon0/device/temp1_input ]
then
	TEMPERATURE=`cat /sys/class/hwmon/hwmon0/device/temp1_input`
	OUTPUT=`echo $TEMPERATURE | awk '{printf( "%." 3 "f\n", $1 / 1000) }' `
	echo $OUTPUT
else
	echo "This only works on the Beaglebone Black single-board computer."
	exit 1
fi
