#!/bin/bash

# Display CPU temperature. Originally inspired by Brian Heckathorne.
# Only works on the Beaglebone Black, under debian!

if [[ ! -f /sys/class/hwmon/hwmon0/device/temp1_input ]]; then
	echo "This only works on the Beaglebone Black single-board computer."
	exit 1

elif [[ "$1" = "--help" ]]; then
	echo "Usage: $ temperature [-q]"
	echo "Default behavior is to display temperature in Celsius as XX.XXX"
	echo "-q: truncate output number to be the integer part."

elif [[ "$1" = "-q" ]]; then
	cut -c-2 < /sys/class/hwmon/hwmon0/device/temp1_input

elif [[ -z $1 ]]; then
        awk '{printf( "%." 3 "f\n", $1 / 1000) }' /sys/class/hwmon/hwmon0/device/temp1_input
fi
